package com.talkweb.study.mappers;

import com.talkweb.study.pojos.BassQueryMain;
import com.talkweb.study.pojos.BassQueryMainExample;
import java.util.List;

public interface BassQueryMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long queryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    int insert(BassQueryMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    int insertSelective(BassQueryMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    List<BassQueryMain> selectByExampleWithBLOBs(BassQueryMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    List<BassQueryMain> selectByExample(BassQueryMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    BassQueryMain selectByPrimaryKey(Long queryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BassQueryMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BassQueryMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BassQueryMain record);
}