package com.talkweb.study.pojos;

import java.util.Date;

public class BassQueryMain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.QUERY_ID
     *
     * @mbggenerated
     */
    private Long queryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.DS_ID
     *
     * @mbggenerated
     */
    private String dsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.QUERY_NAME
     *
     * @mbggenerated
     */
    private String queryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.QUERY_RS
     *
     * @mbggenerated
     */
    private String queryRs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.CREATOR_ID
     *
     * @mbggenerated
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.CREATOR_NAME
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.STATE
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.VAILD_TIME
     *
     * @mbggenerated
     */
    private Date vaildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.INVAILD_TIME
     *
     * @mbggenerated
     */
    private Date invaildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.PAGING_FLAG
     *
     * @mbggenerated
     */
    private Integer pagingFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.PAGING_SIZE
     *
     * @mbggenerated
     */
    private Integer pagingSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.PREVIEW_FLAG
     *
     * @mbggenerated
     */
    private Integer previewFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.PREVIEW_SIZE
     *
     * @mbggenerated
     */
    private Integer previewSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.EXPORT_FLAG
     *
     * @mbggenerated
     */
    private Integer exportFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.DEFAULT_ORDER
     *
     * @mbggenerated
     */
    private String defaultOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.QUERY_RS_SUFFIX
     *
     * @mbggenerated
     */
    private String queryRsSuffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.QUERY_REMARKS
     *
     * @mbggenerated
     */
    private String queryRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.FIXED_WHERE
     *
     * @mbggenerated
     */
    private String fixedWhere;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.LOCK_TITEL_CONFIG
     *
     * @mbggenerated
     */
    private String lockTitelConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.UNLOCK_TITEL_CONFIG
     *
     * @mbggenerated
     */
    private String unlockTitelConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.HAS_TITLE_CONFIG
     *
     * @mbggenerated
     */
    private Integer hasTitleConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.MERGECOLUMNS
     *
     * @mbggenerated
     */
    private String mergecolumns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.BUSINESS_DESC
     *
     * @mbggenerated
     */
    private String businessDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.CREATOR_PHONE
     *
     * @mbggenerated
     */
    private String creatorPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.TIPS
     *
     * @mbggenerated
     */
    private String tips;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.EXT_BUTTONS
     *
     * @mbggenerated
     */
    private String extButtons;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bass_query_main.QUERY_XML
     *
     * @mbggenerated
     */
    private byte[] queryXml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.QUERY_ID
     *
     * @return the value of bass_query_main.QUERY_ID
     *
     * @mbggenerated
     */
    public Long getQueryId() {
        return queryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.QUERY_ID
     *
     * @param queryId the value for bass_query_main.QUERY_ID
     *
     * @mbggenerated
     */
    public void setQueryId(Long queryId) {
        this.queryId = queryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.DS_ID
     *
     * @return the value of bass_query_main.DS_ID
     *
     * @mbggenerated
     */
    public String getDsId() {
        return dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.DS_ID
     *
     * @param dsId the value for bass_query_main.DS_ID
     *
     * @mbggenerated
     */
    public void setDsId(String dsId) {
        this.dsId = dsId == null ? null : dsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.QUERY_NAME
     *
     * @return the value of bass_query_main.QUERY_NAME
     *
     * @mbggenerated
     */
    public String getQueryName() {
        return queryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.QUERY_NAME
     *
     * @param queryName the value for bass_query_main.QUERY_NAME
     *
     * @mbggenerated
     */
    public void setQueryName(String queryName) {
        this.queryName = queryName == null ? null : queryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.QUERY_RS
     *
     * @return the value of bass_query_main.QUERY_RS
     *
     * @mbggenerated
     */
    public String getQueryRs() {
        return queryRs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.QUERY_RS
     *
     * @param queryRs the value for bass_query_main.QUERY_RS
     *
     * @mbggenerated
     */
    public void setQueryRs(String queryRs) {
        this.queryRs = queryRs == null ? null : queryRs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.CREATOR_ID
     *
     * @return the value of bass_query_main.CREATOR_ID
     *
     * @mbggenerated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.CREATOR_ID
     *
     * @param creatorId the value for bass_query_main.CREATOR_ID
     *
     * @mbggenerated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.CREATOR_NAME
     *
     * @return the value of bass_query_main.CREATOR_NAME
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.CREATOR_NAME
     *
     * @param creatorName the value for bass_query_main.CREATOR_NAME
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.STATE
     *
     * @return the value of bass_query_main.STATE
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.STATE
     *
     * @param state the value for bass_query_main.STATE
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.CREATE_TIME
     *
     * @return the value of bass_query_main.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.CREATE_TIME
     *
     * @param createTime the value for bass_query_main.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.VAILD_TIME
     *
     * @return the value of bass_query_main.VAILD_TIME
     *
     * @mbggenerated
     */
    public Date getVaildTime() {
        return vaildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.VAILD_TIME
     *
     * @param vaildTime the value for bass_query_main.VAILD_TIME
     *
     * @mbggenerated
     */
    public void setVaildTime(Date vaildTime) {
        this.vaildTime = vaildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.INVAILD_TIME
     *
     * @return the value of bass_query_main.INVAILD_TIME
     *
     * @mbggenerated
     */
    public Date getInvaildTime() {
        return invaildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.INVAILD_TIME
     *
     * @param invaildTime the value for bass_query_main.INVAILD_TIME
     *
     * @mbggenerated
     */
    public void setInvaildTime(Date invaildTime) {
        this.invaildTime = invaildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.PAGING_FLAG
     *
     * @return the value of bass_query_main.PAGING_FLAG
     *
     * @mbggenerated
     */
    public Integer getPagingFlag() {
        return pagingFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.PAGING_FLAG
     *
     * @param pagingFlag the value for bass_query_main.PAGING_FLAG
     *
     * @mbggenerated
     */
    public void setPagingFlag(Integer pagingFlag) {
        this.pagingFlag = pagingFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.PAGING_SIZE
     *
     * @return the value of bass_query_main.PAGING_SIZE
     *
     * @mbggenerated
     */
    public Integer getPagingSize() {
        return pagingSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.PAGING_SIZE
     *
     * @param pagingSize the value for bass_query_main.PAGING_SIZE
     *
     * @mbggenerated
     */
    public void setPagingSize(Integer pagingSize) {
        this.pagingSize = pagingSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.PREVIEW_FLAG
     *
     * @return the value of bass_query_main.PREVIEW_FLAG
     *
     * @mbggenerated
     */
    public Integer getPreviewFlag() {
        return previewFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.PREVIEW_FLAG
     *
     * @param previewFlag the value for bass_query_main.PREVIEW_FLAG
     *
     * @mbggenerated
     */
    public void setPreviewFlag(Integer previewFlag) {
        this.previewFlag = previewFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.PREVIEW_SIZE
     *
     * @return the value of bass_query_main.PREVIEW_SIZE
     *
     * @mbggenerated
     */
    public Integer getPreviewSize() {
        return previewSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.PREVIEW_SIZE
     *
     * @param previewSize the value for bass_query_main.PREVIEW_SIZE
     *
     * @mbggenerated
     */
    public void setPreviewSize(Integer previewSize) {
        this.previewSize = previewSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.EXPORT_FLAG
     *
     * @return the value of bass_query_main.EXPORT_FLAG
     *
     * @mbggenerated
     */
    public Integer getExportFlag() {
        return exportFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.EXPORT_FLAG
     *
     * @param exportFlag the value for bass_query_main.EXPORT_FLAG
     *
     * @mbggenerated
     */
    public void setExportFlag(Integer exportFlag) {
        this.exportFlag = exportFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.DEFAULT_ORDER
     *
     * @return the value of bass_query_main.DEFAULT_ORDER
     *
     * @mbggenerated
     */
    public String getDefaultOrder() {
        return defaultOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.DEFAULT_ORDER
     *
     * @param defaultOrder the value for bass_query_main.DEFAULT_ORDER
     *
     * @mbggenerated
     */
    public void setDefaultOrder(String defaultOrder) {
        this.defaultOrder = defaultOrder == null ? null : defaultOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.QUERY_RS_SUFFIX
     *
     * @return the value of bass_query_main.QUERY_RS_SUFFIX
     *
     * @mbggenerated
     */
    public String getQueryRsSuffix() {
        return queryRsSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.QUERY_RS_SUFFIX
     *
     * @param queryRsSuffix the value for bass_query_main.QUERY_RS_SUFFIX
     *
     * @mbggenerated
     */
    public void setQueryRsSuffix(String queryRsSuffix) {
        this.queryRsSuffix = queryRsSuffix == null ? null : queryRsSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.QUERY_REMARKS
     *
     * @return the value of bass_query_main.QUERY_REMARKS
     *
     * @mbggenerated
     */
    public String getQueryRemarks() {
        return queryRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.QUERY_REMARKS
     *
     * @param queryRemarks the value for bass_query_main.QUERY_REMARKS
     *
     * @mbggenerated
     */
    public void setQueryRemarks(String queryRemarks) {
        this.queryRemarks = queryRemarks == null ? null : queryRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.FIXED_WHERE
     *
     * @return the value of bass_query_main.FIXED_WHERE
     *
     * @mbggenerated
     */
    public String getFixedWhere() {
        return fixedWhere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.FIXED_WHERE
     *
     * @param fixedWhere the value for bass_query_main.FIXED_WHERE
     *
     * @mbggenerated
     */
    public void setFixedWhere(String fixedWhere) {
        this.fixedWhere = fixedWhere == null ? null : fixedWhere.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.LOCK_TITEL_CONFIG
     *
     * @return the value of bass_query_main.LOCK_TITEL_CONFIG
     *
     * @mbggenerated
     */
    public String getLockTitelConfig() {
        return lockTitelConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.LOCK_TITEL_CONFIG
     *
     * @param lockTitelConfig the value for bass_query_main.LOCK_TITEL_CONFIG
     *
     * @mbggenerated
     */
    public void setLockTitelConfig(String lockTitelConfig) {
        this.lockTitelConfig = lockTitelConfig == null ? null : lockTitelConfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.UNLOCK_TITEL_CONFIG
     *
     * @return the value of bass_query_main.UNLOCK_TITEL_CONFIG
     *
     * @mbggenerated
     */
    public String getUnlockTitelConfig() {
        return unlockTitelConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.UNLOCK_TITEL_CONFIG
     *
     * @param unlockTitelConfig the value for bass_query_main.UNLOCK_TITEL_CONFIG
     *
     * @mbggenerated
     */
    public void setUnlockTitelConfig(String unlockTitelConfig) {
        this.unlockTitelConfig = unlockTitelConfig == null ? null : unlockTitelConfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.HAS_TITLE_CONFIG
     *
     * @return the value of bass_query_main.HAS_TITLE_CONFIG
     *
     * @mbggenerated
     */
    public Integer getHasTitleConfig() {
        return hasTitleConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.HAS_TITLE_CONFIG
     *
     * @param hasTitleConfig the value for bass_query_main.HAS_TITLE_CONFIG
     *
     * @mbggenerated
     */
    public void setHasTitleConfig(Integer hasTitleConfig) {
        this.hasTitleConfig = hasTitleConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.MERGECOLUMNS
     *
     * @return the value of bass_query_main.MERGECOLUMNS
     *
     * @mbggenerated
     */
    public String getMergecolumns() {
        return mergecolumns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.MERGECOLUMNS
     *
     * @param mergecolumns the value for bass_query_main.MERGECOLUMNS
     *
     * @mbggenerated
     */
    public void setMergecolumns(String mergecolumns) {
        this.mergecolumns = mergecolumns == null ? null : mergecolumns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.BUSINESS_DESC
     *
     * @return the value of bass_query_main.BUSINESS_DESC
     *
     * @mbggenerated
     */
    public String getBusinessDesc() {
        return businessDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.BUSINESS_DESC
     *
     * @param businessDesc the value for bass_query_main.BUSINESS_DESC
     *
     * @mbggenerated
     */
    public void setBusinessDesc(String businessDesc) {
        this.businessDesc = businessDesc == null ? null : businessDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.CREATOR_PHONE
     *
     * @return the value of bass_query_main.CREATOR_PHONE
     *
     * @mbggenerated
     */
    public String getCreatorPhone() {
        return creatorPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.CREATOR_PHONE
     *
     * @param creatorPhone the value for bass_query_main.CREATOR_PHONE
     *
     * @mbggenerated
     */
    public void setCreatorPhone(String creatorPhone) {
        this.creatorPhone = creatorPhone == null ? null : creatorPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.TIPS
     *
     * @return the value of bass_query_main.TIPS
     *
     * @mbggenerated
     */
    public String getTips() {
        return tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.TIPS
     *
     * @param tips the value for bass_query_main.TIPS
     *
     * @mbggenerated
     */
    public void setTips(String tips) {
        this.tips = tips == null ? null : tips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.EXT_BUTTONS
     *
     * @return the value of bass_query_main.EXT_BUTTONS
     *
     * @mbggenerated
     */
    public String getExtButtons() {
        return extButtons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.EXT_BUTTONS
     *
     * @param extButtons the value for bass_query_main.EXT_BUTTONS
     *
     * @mbggenerated
     */
    public void setExtButtons(String extButtons) {
        this.extButtons = extButtons == null ? null : extButtons.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bass_query_main.QUERY_XML
     *
     * @return the value of bass_query_main.QUERY_XML
     *
     * @mbggenerated
     */
    public byte[] getQueryXml() {
        return queryXml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bass_query_main.QUERY_XML
     *
     * @param queryXml the value for bass_query_main.QUERY_XML
     *
     * @mbggenerated
     */
    public void setQueryXml(byte[] queryXml) {
        this.queryXml = queryXml;
    }
}