package com.talkweb.study.pojos;

import com.zaxk.study.mybatis.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BassQueryMainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    public BassQueryMainExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQueryIdIsNull() {
            addCriterion("QUERY_ID is null");
            return (Criteria) this;
        }

        public Criteria andQueryIdIsNotNull() {
            addCriterion("QUERY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andQueryIdEqualTo(Long value) {
            addCriterion("QUERY_ID =", value, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdNotEqualTo(Long value) {
            addCriterion("QUERY_ID <>", value, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdGreaterThan(Long value) {
            addCriterion("QUERY_ID >", value, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("QUERY_ID >=", value, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdLessThan(Long value) {
            addCriterion("QUERY_ID <", value, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdLessThanOrEqualTo(Long value) {
            addCriterion("QUERY_ID <=", value, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdIn(List<Long> values) {
            addCriterion("QUERY_ID in", values, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdNotIn(List<Long> values) {
            addCriterion("QUERY_ID not in", values, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdBetween(Long value1, Long value2) {
            addCriterion("QUERY_ID between", value1, value2, "queryId");
            return (Criteria) this;
        }

        public Criteria andQueryIdNotBetween(Long value1, Long value2) {
            addCriterion("QUERY_ID not between", value1, value2, "queryId");
            return (Criteria) this;
        }

        public Criteria andDsIdIsNull() {
            addCriterion("DS_ID is null");
            return (Criteria) this;
        }

        public Criteria andDsIdIsNotNull() {
            addCriterion("DS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDsIdEqualTo(String value) {
            addCriterion("DS_ID =", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdNotEqualTo(String value) {
            addCriterion("DS_ID <>", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdGreaterThan(String value) {
            addCriterion("DS_ID >", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdGreaterThanOrEqualTo(String value) {
            addCriterion("DS_ID >=", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdLessThan(String value) {
            addCriterion("DS_ID <", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdLessThanOrEqualTo(String value) {
            addCriterion("DS_ID <=", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdLike(String value) {
            addCriterion("DS_ID like", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdNotLike(String value) {
            addCriterion("DS_ID not like", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdIn(List<String> values) {
            addCriterion("DS_ID in", values, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdNotIn(List<String> values) {
            addCriterion("DS_ID not in", values, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdBetween(String value1, String value2) {
            addCriterion("DS_ID between", value1, value2, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdNotBetween(String value1, String value2) {
            addCriterion("DS_ID not between", value1, value2, "dsId");
            return (Criteria) this;
        }

        public Criteria andQueryNameIsNull() {
            addCriterion("QUERY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andQueryNameIsNotNull() {
            addCriterion("QUERY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andQueryNameEqualTo(String value) {
            addCriterion("QUERY_NAME =", value, "queryName");
            return (Criteria) this;
        }

        public Criteria andQueryNameNotEqualTo(String value) {
            addCriterion("QUERY_NAME <>", value, "queryName");
            return (Criteria) this;
        }

        public Criteria andQueryNameGreaterThan(String value) {
            addCriterion("QUERY_NAME >", value, "queryName");
            return (Criteria) this;
        }

        public Criteria andQueryNameGreaterThanOrEqualTo(String value) {
            addCriterion("QUERY_NAME >=", value, "queryName");
            return (Criteria) this;
        }

        public Criteria andQueryNameLessThan(String value) {
            addCriterion("QUERY_NAME <", value, "queryName");
            return (Criteria) this;
        }

        public Criteria andQueryNameLessThanOrEqualTo(String value) {
            addCriterion("QUERY_NAME <=", value, "queryName");
            return (Criteria) this;
        }

        public Criteria andQueryNameLike(String value) {
            addCriterion("QUERY_NAME like", value, "queryName");
            return (Criteria) this;
        }

        public Criteria andQueryNameNotLike(String value) {
            addCriterion("QUERY_NAME not like", value, "queryName");
            return (Criteria) this;
        }

        public Criteria andQueryNameIn(List<String> values) {
            addCriterion("QUERY_NAME in", values, "queryName");
            return (Criteria) this;
        }

        public Criteria andQueryNameNotIn(List<String> values) {
            addCriterion("QUERY_NAME not in", values, "queryName");
            return (Criteria) this;
        }

        public Criteria andQueryNameBetween(String value1, String value2) {
            addCriterion("QUERY_NAME between", value1, value2, "queryName");
            return (Criteria) this;
        }

        public Criteria andQueryNameNotBetween(String value1, String value2) {
            addCriterion("QUERY_NAME not between", value1, value2, "queryName");
            return (Criteria) this;
        }

        public Criteria andQueryRsIsNull() {
            addCriterion("QUERY_RS is null");
            return (Criteria) this;
        }

        public Criteria andQueryRsIsNotNull() {
            addCriterion("QUERY_RS is not null");
            return (Criteria) this;
        }

        public Criteria andQueryRsEqualTo(String value) {
            addCriterion("QUERY_RS =", value, "queryRs");
            return (Criteria) this;
        }

        public Criteria andQueryRsNotEqualTo(String value) {
            addCriterion("QUERY_RS <>", value, "queryRs");
            return (Criteria) this;
        }

        public Criteria andQueryRsGreaterThan(String value) {
            addCriterion("QUERY_RS >", value, "queryRs");
            return (Criteria) this;
        }

        public Criteria andQueryRsGreaterThanOrEqualTo(String value) {
            addCriterion("QUERY_RS >=", value, "queryRs");
            return (Criteria) this;
        }

        public Criteria andQueryRsLessThan(String value) {
            addCriterion("QUERY_RS <", value, "queryRs");
            return (Criteria) this;
        }

        public Criteria andQueryRsLessThanOrEqualTo(String value) {
            addCriterion("QUERY_RS <=", value, "queryRs");
            return (Criteria) this;
        }

        public Criteria andQueryRsLike(String value) {
            addCriterion("QUERY_RS like", value, "queryRs");
            return (Criteria) this;
        }

        public Criteria andQueryRsNotLike(String value) {
            addCriterion("QUERY_RS not like", value, "queryRs");
            return (Criteria) this;
        }

        public Criteria andQueryRsIn(List<String> values) {
            addCriterion("QUERY_RS in", values, "queryRs");
            return (Criteria) this;
        }

        public Criteria andQueryRsNotIn(List<String> values) {
            addCriterion("QUERY_RS not in", values, "queryRs");
            return (Criteria) this;
        }

        public Criteria andQueryRsBetween(String value1, String value2) {
            addCriterion("QUERY_RS between", value1, value2, "queryRs");
            return (Criteria) this;
        }

        public Criteria andQueryRsNotBetween(String value1, String value2) {
            addCriterion("QUERY_RS not between", value1, value2, "queryRs");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNull() {
            addCriterion("CREATOR_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNotNull() {
            addCriterion("CREATOR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdEqualTo(String value) {
            addCriterion("CREATOR_ID =", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotEqualTo(String value) {
            addCriterion("CREATOR_ID <>", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThan(String value) {
            addCriterion("CREATOR_ID >", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR_ID >=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThan(String value) {
            addCriterion("CREATOR_ID <", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThanOrEqualTo(String value) {
            addCriterion("CREATOR_ID <=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLike(String value) {
            addCriterion("CREATOR_ID like", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotLike(String value) {
            addCriterion("CREATOR_ID not like", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIn(List<String> values) {
            addCriterion("CREATOR_ID in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotIn(List<String> values) {
            addCriterion("CREATOR_ID not in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdBetween(String value1, String value2) {
            addCriterion("CREATOR_ID between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotBetween(String value1, String value2) {
            addCriterion("CREATOR_ID not between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorNameIsNull() {
            addCriterion("CREATOR_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCreatorNameIsNotNull() {
            addCriterion("CREATOR_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorNameEqualTo(String value) {
            addCriterion("CREATOR_NAME =", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotEqualTo(String value) {
            addCriterion("CREATOR_NAME <>", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameGreaterThan(String value) {
            addCriterion("CREATOR_NAME >", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR_NAME >=", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameLessThan(String value) {
            addCriterion("CREATOR_NAME <", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameLessThanOrEqualTo(String value) {
            addCriterion("CREATOR_NAME <=", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameLike(String value) {
            addCriterion("CREATOR_NAME like", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotLike(String value) {
            addCriterion("CREATOR_NAME not like", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameIn(List<String> values) {
            addCriterion("CREATOR_NAME in", values, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotIn(List<String> values) {
            addCriterion("CREATOR_NAME not in", values, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameBetween(String value1, String value2) {
            addCriterion("CREATOR_NAME between", value1, value2, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotBetween(String value1, String value2) {
            addCriterion("CREATOR_NAME not between", value1, value2, "creatorName");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andVaildTimeIsNull() {
            addCriterion("VAILD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andVaildTimeIsNotNull() {
            addCriterion("VAILD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andVaildTimeEqualTo(Date value) {
            addCriterion("VAILD_TIME =", value, "vaildTime");
            return (Criteria) this;
        }

        public Criteria andVaildTimeNotEqualTo(Date value) {
            addCriterion("VAILD_TIME <>", value, "vaildTime");
            return (Criteria) this;
        }

        public Criteria andVaildTimeGreaterThan(Date value) {
            addCriterion("VAILD_TIME >", value, "vaildTime");
            return (Criteria) this;
        }

        public Criteria andVaildTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("VAILD_TIME >=", value, "vaildTime");
            return (Criteria) this;
        }

        public Criteria andVaildTimeLessThan(Date value) {
            addCriterion("VAILD_TIME <", value, "vaildTime");
            return (Criteria) this;
        }

        public Criteria andVaildTimeLessThanOrEqualTo(Date value) {
            addCriterion("VAILD_TIME <=", value, "vaildTime");
            return (Criteria) this;
        }

        public Criteria andVaildTimeIn(List<Date> values) {
            addCriterion("VAILD_TIME in", values, "vaildTime");
            return (Criteria) this;
        }

        public Criteria andVaildTimeNotIn(List<Date> values) {
            addCriterion("VAILD_TIME not in", values, "vaildTime");
            return (Criteria) this;
        }

        public Criteria andVaildTimeBetween(Date value1, Date value2) {
            addCriterion("VAILD_TIME between", value1, value2, "vaildTime");
            return (Criteria) this;
        }

        public Criteria andVaildTimeNotBetween(Date value1, Date value2) {
            addCriterion("VAILD_TIME not between", value1, value2, "vaildTime");
            return (Criteria) this;
        }

        public Criteria andInvaildTimeIsNull() {
            addCriterion("INVAILD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andInvaildTimeIsNotNull() {
            addCriterion("INVAILD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andInvaildTimeEqualTo(Date value) {
            addCriterion("INVAILD_TIME =", value, "invaildTime");
            return (Criteria) this;
        }

        public Criteria andInvaildTimeNotEqualTo(Date value) {
            addCriterion("INVAILD_TIME <>", value, "invaildTime");
            return (Criteria) this;
        }

        public Criteria andInvaildTimeGreaterThan(Date value) {
            addCriterion("INVAILD_TIME >", value, "invaildTime");
            return (Criteria) this;
        }

        public Criteria andInvaildTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("INVAILD_TIME >=", value, "invaildTime");
            return (Criteria) this;
        }

        public Criteria andInvaildTimeLessThan(Date value) {
            addCriterion("INVAILD_TIME <", value, "invaildTime");
            return (Criteria) this;
        }

        public Criteria andInvaildTimeLessThanOrEqualTo(Date value) {
            addCriterion("INVAILD_TIME <=", value, "invaildTime");
            return (Criteria) this;
        }

        public Criteria andInvaildTimeIn(List<Date> values) {
            addCriterion("INVAILD_TIME in", values, "invaildTime");
            return (Criteria) this;
        }

        public Criteria andInvaildTimeNotIn(List<Date> values) {
            addCriterion("INVAILD_TIME not in", values, "invaildTime");
            return (Criteria) this;
        }

        public Criteria andInvaildTimeBetween(Date value1, Date value2) {
            addCriterion("INVAILD_TIME between", value1, value2, "invaildTime");
            return (Criteria) this;
        }

        public Criteria andInvaildTimeNotBetween(Date value1, Date value2) {
            addCriterion("INVAILD_TIME not between", value1, value2, "invaildTime");
            return (Criteria) this;
        }

        public Criteria andPagingFlagIsNull() {
            addCriterion("PAGING_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andPagingFlagIsNotNull() {
            addCriterion("PAGING_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andPagingFlagEqualTo(Integer value) {
            addCriterion("PAGING_FLAG =", value, "pagingFlag");
            return (Criteria) this;
        }

        public Criteria andPagingFlagNotEqualTo(Integer value) {
            addCriterion("PAGING_FLAG <>", value, "pagingFlag");
            return (Criteria) this;
        }

        public Criteria andPagingFlagGreaterThan(Integer value) {
            addCriterion("PAGING_FLAG >", value, "pagingFlag");
            return (Criteria) this;
        }

        public Criteria andPagingFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("PAGING_FLAG >=", value, "pagingFlag");
            return (Criteria) this;
        }

        public Criteria andPagingFlagLessThan(Integer value) {
            addCriterion("PAGING_FLAG <", value, "pagingFlag");
            return (Criteria) this;
        }

        public Criteria andPagingFlagLessThanOrEqualTo(Integer value) {
            addCriterion("PAGING_FLAG <=", value, "pagingFlag");
            return (Criteria) this;
        }

        public Criteria andPagingFlagIn(List<Integer> values) {
            addCriterion("PAGING_FLAG in", values, "pagingFlag");
            return (Criteria) this;
        }

        public Criteria andPagingFlagNotIn(List<Integer> values) {
            addCriterion("PAGING_FLAG not in", values, "pagingFlag");
            return (Criteria) this;
        }

        public Criteria andPagingFlagBetween(Integer value1, Integer value2) {
            addCriterion("PAGING_FLAG between", value1, value2, "pagingFlag");
            return (Criteria) this;
        }

        public Criteria andPagingFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("PAGING_FLAG not between", value1, value2, "pagingFlag");
            return (Criteria) this;
        }

        public Criteria andPagingSizeIsNull() {
            addCriterion("PAGING_SIZE is null");
            return (Criteria) this;
        }

        public Criteria andPagingSizeIsNotNull() {
            addCriterion("PAGING_SIZE is not null");
            return (Criteria) this;
        }

        public Criteria andPagingSizeEqualTo(Integer value) {
            addCriterion("PAGING_SIZE =", value, "pagingSize");
            return (Criteria) this;
        }

        public Criteria andPagingSizeNotEqualTo(Integer value) {
            addCriterion("PAGING_SIZE <>", value, "pagingSize");
            return (Criteria) this;
        }

        public Criteria andPagingSizeGreaterThan(Integer value) {
            addCriterion("PAGING_SIZE >", value, "pagingSize");
            return (Criteria) this;
        }

        public Criteria andPagingSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PAGING_SIZE >=", value, "pagingSize");
            return (Criteria) this;
        }

        public Criteria andPagingSizeLessThan(Integer value) {
            addCriterion("PAGING_SIZE <", value, "pagingSize");
            return (Criteria) this;
        }

        public Criteria andPagingSizeLessThanOrEqualTo(Integer value) {
            addCriterion("PAGING_SIZE <=", value, "pagingSize");
            return (Criteria) this;
        }

        public Criteria andPagingSizeIn(List<Integer> values) {
            addCriterion("PAGING_SIZE in", values, "pagingSize");
            return (Criteria) this;
        }

        public Criteria andPagingSizeNotIn(List<Integer> values) {
            addCriterion("PAGING_SIZE not in", values, "pagingSize");
            return (Criteria) this;
        }

        public Criteria andPagingSizeBetween(Integer value1, Integer value2) {
            addCriterion("PAGING_SIZE between", value1, value2, "pagingSize");
            return (Criteria) this;
        }

        public Criteria andPagingSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("PAGING_SIZE not between", value1, value2, "pagingSize");
            return (Criteria) this;
        }

        public Criteria andPreviewFlagIsNull() {
            addCriterion("PREVIEW_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andPreviewFlagIsNotNull() {
            addCriterion("PREVIEW_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andPreviewFlagEqualTo(Integer value) {
            addCriterion("PREVIEW_FLAG =", value, "previewFlag");
            return (Criteria) this;
        }

        public Criteria andPreviewFlagNotEqualTo(Integer value) {
            addCriterion("PREVIEW_FLAG <>", value, "previewFlag");
            return (Criteria) this;
        }

        public Criteria andPreviewFlagGreaterThan(Integer value) {
            addCriterion("PREVIEW_FLAG >", value, "previewFlag");
            return (Criteria) this;
        }

        public Criteria andPreviewFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("PREVIEW_FLAG >=", value, "previewFlag");
            return (Criteria) this;
        }

        public Criteria andPreviewFlagLessThan(Integer value) {
            addCriterion("PREVIEW_FLAG <", value, "previewFlag");
            return (Criteria) this;
        }

        public Criteria andPreviewFlagLessThanOrEqualTo(Integer value) {
            addCriterion("PREVIEW_FLAG <=", value, "previewFlag");
            return (Criteria) this;
        }

        public Criteria andPreviewFlagIn(List<Integer> values) {
            addCriterion("PREVIEW_FLAG in", values, "previewFlag");
            return (Criteria) this;
        }

        public Criteria andPreviewFlagNotIn(List<Integer> values) {
            addCriterion("PREVIEW_FLAG not in", values, "previewFlag");
            return (Criteria) this;
        }

        public Criteria andPreviewFlagBetween(Integer value1, Integer value2) {
            addCriterion("PREVIEW_FLAG between", value1, value2, "previewFlag");
            return (Criteria) this;
        }

        public Criteria andPreviewFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("PREVIEW_FLAG not between", value1, value2, "previewFlag");
            return (Criteria) this;
        }

        public Criteria andPreviewSizeIsNull() {
            addCriterion("PREVIEW_SIZE is null");
            return (Criteria) this;
        }

        public Criteria andPreviewSizeIsNotNull() {
            addCriterion("PREVIEW_SIZE is not null");
            return (Criteria) this;
        }

        public Criteria andPreviewSizeEqualTo(Integer value) {
            addCriterion("PREVIEW_SIZE =", value, "previewSize");
            return (Criteria) this;
        }

        public Criteria andPreviewSizeNotEqualTo(Integer value) {
            addCriterion("PREVIEW_SIZE <>", value, "previewSize");
            return (Criteria) this;
        }

        public Criteria andPreviewSizeGreaterThan(Integer value) {
            addCriterion("PREVIEW_SIZE >", value, "previewSize");
            return (Criteria) this;
        }

        public Criteria andPreviewSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PREVIEW_SIZE >=", value, "previewSize");
            return (Criteria) this;
        }

        public Criteria andPreviewSizeLessThan(Integer value) {
            addCriterion("PREVIEW_SIZE <", value, "previewSize");
            return (Criteria) this;
        }

        public Criteria andPreviewSizeLessThanOrEqualTo(Integer value) {
            addCriterion("PREVIEW_SIZE <=", value, "previewSize");
            return (Criteria) this;
        }

        public Criteria andPreviewSizeIn(List<Integer> values) {
            addCriterion("PREVIEW_SIZE in", values, "previewSize");
            return (Criteria) this;
        }

        public Criteria andPreviewSizeNotIn(List<Integer> values) {
            addCriterion("PREVIEW_SIZE not in", values, "previewSize");
            return (Criteria) this;
        }

        public Criteria andPreviewSizeBetween(Integer value1, Integer value2) {
            addCriterion("PREVIEW_SIZE between", value1, value2, "previewSize");
            return (Criteria) this;
        }

        public Criteria andPreviewSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("PREVIEW_SIZE not between", value1, value2, "previewSize");
            return (Criteria) this;
        }

        public Criteria andExportFlagIsNull() {
            addCriterion("EXPORT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andExportFlagIsNotNull() {
            addCriterion("EXPORT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andExportFlagEqualTo(Integer value) {
            addCriterion("EXPORT_FLAG =", value, "exportFlag");
            return (Criteria) this;
        }

        public Criteria andExportFlagNotEqualTo(Integer value) {
            addCriterion("EXPORT_FLAG <>", value, "exportFlag");
            return (Criteria) this;
        }

        public Criteria andExportFlagGreaterThan(Integer value) {
            addCriterion("EXPORT_FLAG >", value, "exportFlag");
            return (Criteria) this;
        }

        public Criteria andExportFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("EXPORT_FLAG >=", value, "exportFlag");
            return (Criteria) this;
        }

        public Criteria andExportFlagLessThan(Integer value) {
            addCriterion("EXPORT_FLAG <", value, "exportFlag");
            return (Criteria) this;
        }

        public Criteria andExportFlagLessThanOrEqualTo(Integer value) {
            addCriterion("EXPORT_FLAG <=", value, "exportFlag");
            return (Criteria) this;
        }

        public Criteria andExportFlagIn(List<Integer> values) {
            addCriterion("EXPORT_FLAG in", values, "exportFlag");
            return (Criteria) this;
        }

        public Criteria andExportFlagNotIn(List<Integer> values) {
            addCriterion("EXPORT_FLAG not in", values, "exportFlag");
            return (Criteria) this;
        }

        public Criteria andExportFlagBetween(Integer value1, Integer value2) {
            addCriterion("EXPORT_FLAG between", value1, value2, "exportFlag");
            return (Criteria) this;
        }

        public Criteria andExportFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("EXPORT_FLAG not between", value1, value2, "exportFlag");
            return (Criteria) this;
        }

        public Criteria andDefaultOrderIsNull() {
            addCriterion("DEFAULT_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andDefaultOrderIsNotNull() {
            addCriterion("DEFAULT_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultOrderEqualTo(String value) {
            addCriterion("DEFAULT_ORDER =", value, "defaultOrder");
            return (Criteria) this;
        }

        public Criteria andDefaultOrderNotEqualTo(String value) {
            addCriterion("DEFAULT_ORDER <>", value, "defaultOrder");
            return (Criteria) this;
        }

        public Criteria andDefaultOrderGreaterThan(String value) {
            addCriterion("DEFAULT_ORDER >", value, "defaultOrder");
            return (Criteria) this;
        }

        public Criteria andDefaultOrderGreaterThanOrEqualTo(String value) {
            addCriterion("DEFAULT_ORDER >=", value, "defaultOrder");
            return (Criteria) this;
        }

        public Criteria andDefaultOrderLessThan(String value) {
            addCriterion("DEFAULT_ORDER <", value, "defaultOrder");
            return (Criteria) this;
        }

        public Criteria andDefaultOrderLessThanOrEqualTo(String value) {
            addCriterion("DEFAULT_ORDER <=", value, "defaultOrder");
            return (Criteria) this;
        }

        public Criteria andDefaultOrderLike(String value) {
            addCriterion("DEFAULT_ORDER like", value, "defaultOrder");
            return (Criteria) this;
        }

        public Criteria andDefaultOrderNotLike(String value) {
            addCriterion("DEFAULT_ORDER not like", value, "defaultOrder");
            return (Criteria) this;
        }

        public Criteria andDefaultOrderIn(List<String> values) {
            addCriterion("DEFAULT_ORDER in", values, "defaultOrder");
            return (Criteria) this;
        }

        public Criteria andDefaultOrderNotIn(List<String> values) {
            addCriterion("DEFAULT_ORDER not in", values, "defaultOrder");
            return (Criteria) this;
        }

        public Criteria andDefaultOrderBetween(String value1, String value2) {
            addCriterion("DEFAULT_ORDER between", value1, value2, "defaultOrder");
            return (Criteria) this;
        }

        public Criteria andDefaultOrderNotBetween(String value1, String value2) {
            addCriterion("DEFAULT_ORDER not between", value1, value2, "defaultOrder");
            return (Criteria) this;
        }

        public Criteria andQueryRsSuffixIsNull() {
            addCriterion("QUERY_RS_SUFFIX is null");
            return (Criteria) this;
        }

        public Criteria andQueryRsSuffixIsNotNull() {
            addCriterion("QUERY_RS_SUFFIX is not null");
            return (Criteria) this;
        }

        public Criteria andQueryRsSuffixEqualTo(String value) {
            addCriterion("QUERY_RS_SUFFIX =", value, "queryRsSuffix");
            return (Criteria) this;
        }

        public Criteria andQueryRsSuffixNotEqualTo(String value) {
            addCriterion("QUERY_RS_SUFFIX <>", value, "queryRsSuffix");
            return (Criteria) this;
        }

        public Criteria andQueryRsSuffixGreaterThan(String value) {
            addCriterion("QUERY_RS_SUFFIX >", value, "queryRsSuffix");
            return (Criteria) this;
        }

        public Criteria andQueryRsSuffixGreaterThanOrEqualTo(String value) {
            addCriterion("QUERY_RS_SUFFIX >=", value, "queryRsSuffix");
            return (Criteria) this;
        }

        public Criteria andQueryRsSuffixLessThan(String value) {
            addCriterion("QUERY_RS_SUFFIX <", value, "queryRsSuffix");
            return (Criteria) this;
        }

        public Criteria andQueryRsSuffixLessThanOrEqualTo(String value) {
            addCriterion("QUERY_RS_SUFFIX <=", value, "queryRsSuffix");
            return (Criteria) this;
        }

        public Criteria andQueryRsSuffixLike(String value) {
            addCriterion("QUERY_RS_SUFFIX like", value, "queryRsSuffix");
            return (Criteria) this;
        }

        public Criteria andQueryRsSuffixNotLike(String value) {
            addCriterion("QUERY_RS_SUFFIX not like", value, "queryRsSuffix");
            return (Criteria) this;
        }

        public Criteria andQueryRsSuffixIn(List<String> values) {
            addCriterion("QUERY_RS_SUFFIX in", values, "queryRsSuffix");
            return (Criteria) this;
        }

        public Criteria andQueryRsSuffixNotIn(List<String> values) {
            addCriterion("QUERY_RS_SUFFIX not in", values, "queryRsSuffix");
            return (Criteria) this;
        }

        public Criteria andQueryRsSuffixBetween(String value1, String value2) {
            addCriterion("QUERY_RS_SUFFIX between", value1, value2, "queryRsSuffix");
            return (Criteria) this;
        }

        public Criteria andQueryRsSuffixNotBetween(String value1, String value2) {
            addCriterion("QUERY_RS_SUFFIX not between", value1, value2, "queryRsSuffix");
            return (Criteria) this;
        }

        public Criteria andQueryRemarksIsNull() {
            addCriterion("QUERY_REMARKS is null");
            return (Criteria) this;
        }

        public Criteria andQueryRemarksIsNotNull() {
            addCriterion("QUERY_REMARKS is not null");
            return (Criteria) this;
        }

        public Criteria andQueryRemarksEqualTo(String value) {
            addCriterion("QUERY_REMARKS =", value, "queryRemarks");
            return (Criteria) this;
        }

        public Criteria andQueryRemarksNotEqualTo(String value) {
            addCriterion("QUERY_REMARKS <>", value, "queryRemarks");
            return (Criteria) this;
        }

        public Criteria andQueryRemarksGreaterThan(String value) {
            addCriterion("QUERY_REMARKS >", value, "queryRemarks");
            return (Criteria) this;
        }

        public Criteria andQueryRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("QUERY_REMARKS >=", value, "queryRemarks");
            return (Criteria) this;
        }

        public Criteria andQueryRemarksLessThan(String value) {
            addCriterion("QUERY_REMARKS <", value, "queryRemarks");
            return (Criteria) this;
        }

        public Criteria andQueryRemarksLessThanOrEqualTo(String value) {
            addCriterion("QUERY_REMARKS <=", value, "queryRemarks");
            return (Criteria) this;
        }

        public Criteria andQueryRemarksLike(String value) {
            addCriterion("QUERY_REMARKS like", value, "queryRemarks");
            return (Criteria) this;
        }

        public Criteria andQueryRemarksNotLike(String value) {
            addCriterion("QUERY_REMARKS not like", value, "queryRemarks");
            return (Criteria) this;
        }

        public Criteria andQueryRemarksIn(List<String> values) {
            addCriterion("QUERY_REMARKS in", values, "queryRemarks");
            return (Criteria) this;
        }

        public Criteria andQueryRemarksNotIn(List<String> values) {
            addCriterion("QUERY_REMARKS not in", values, "queryRemarks");
            return (Criteria) this;
        }

        public Criteria andQueryRemarksBetween(String value1, String value2) {
            addCriterion("QUERY_REMARKS between", value1, value2, "queryRemarks");
            return (Criteria) this;
        }

        public Criteria andQueryRemarksNotBetween(String value1, String value2) {
            addCriterion("QUERY_REMARKS not between", value1, value2, "queryRemarks");
            return (Criteria) this;
        }

        public Criteria andFixedWhereIsNull() {
            addCriterion("FIXED_WHERE is null");
            return (Criteria) this;
        }

        public Criteria andFixedWhereIsNotNull() {
            addCriterion("FIXED_WHERE is not null");
            return (Criteria) this;
        }

        public Criteria andFixedWhereEqualTo(String value) {
            addCriterion("FIXED_WHERE =", value, "fixedWhere");
            return (Criteria) this;
        }

        public Criteria andFixedWhereNotEqualTo(String value) {
            addCriterion("FIXED_WHERE <>", value, "fixedWhere");
            return (Criteria) this;
        }

        public Criteria andFixedWhereGreaterThan(String value) {
            addCriterion("FIXED_WHERE >", value, "fixedWhere");
            return (Criteria) this;
        }

        public Criteria andFixedWhereGreaterThanOrEqualTo(String value) {
            addCriterion("FIXED_WHERE >=", value, "fixedWhere");
            return (Criteria) this;
        }

        public Criteria andFixedWhereLessThan(String value) {
            addCriterion("FIXED_WHERE <", value, "fixedWhere");
            return (Criteria) this;
        }

        public Criteria andFixedWhereLessThanOrEqualTo(String value) {
            addCriterion("FIXED_WHERE <=", value, "fixedWhere");
            return (Criteria) this;
        }

        public Criteria andFixedWhereLike(String value) {
            addCriterion("FIXED_WHERE like", value, "fixedWhere");
            return (Criteria) this;
        }

        public Criteria andFixedWhereNotLike(String value) {
            addCriterion("FIXED_WHERE not like", value, "fixedWhere");
            return (Criteria) this;
        }

        public Criteria andFixedWhereIn(List<String> values) {
            addCriterion("FIXED_WHERE in", values, "fixedWhere");
            return (Criteria) this;
        }

        public Criteria andFixedWhereNotIn(List<String> values) {
            addCriterion("FIXED_WHERE not in", values, "fixedWhere");
            return (Criteria) this;
        }

        public Criteria andFixedWhereBetween(String value1, String value2) {
            addCriterion("FIXED_WHERE between", value1, value2, "fixedWhere");
            return (Criteria) this;
        }

        public Criteria andFixedWhereNotBetween(String value1, String value2) {
            addCriterion("FIXED_WHERE not between", value1, value2, "fixedWhere");
            return (Criteria) this;
        }

        public Criteria andLockTitelConfigIsNull() {
            addCriterion("LOCK_TITEL_CONFIG is null");
            return (Criteria) this;
        }

        public Criteria andLockTitelConfigIsNotNull() {
            addCriterion("LOCK_TITEL_CONFIG is not null");
            return (Criteria) this;
        }

        public Criteria andLockTitelConfigEqualTo(String value) {
            addCriterion("LOCK_TITEL_CONFIG =", value, "lockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andLockTitelConfigNotEqualTo(String value) {
            addCriterion("LOCK_TITEL_CONFIG <>", value, "lockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andLockTitelConfigGreaterThan(String value) {
            addCriterion("LOCK_TITEL_CONFIG >", value, "lockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andLockTitelConfigGreaterThanOrEqualTo(String value) {
            addCriterion("LOCK_TITEL_CONFIG >=", value, "lockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andLockTitelConfigLessThan(String value) {
            addCriterion("LOCK_TITEL_CONFIG <", value, "lockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andLockTitelConfigLessThanOrEqualTo(String value) {
            addCriterion("LOCK_TITEL_CONFIG <=", value, "lockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andLockTitelConfigLike(String value) {
            addCriterion("LOCK_TITEL_CONFIG like", value, "lockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andLockTitelConfigNotLike(String value) {
            addCriterion("LOCK_TITEL_CONFIG not like", value, "lockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andLockTitelConfigIn(List<String> values) {
            addCriterion("LOCK_TITEL_CONFIG in", values, "lockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andLockTitelConfigNotIn(List<String> values) {
            addCriterion("LOCK_TITEL_CONFIG not in", values, "lockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andLockTitelConfigBetween(String value1, String value2) {
            addCriterion("LOCK_TITEL_CONFIG between", value1, value2, "lockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andLockTitelConfigNotBetween(String value1, String value2) {
            addCriterion("LOCK_TITEL_CONFIG not between", value1, value2, "lockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andUnlockTitelConfigIsNull() {
            addCriterion("UNLOCK_TITEL_CONFIG is null");
            return (Criteria) this;
        }

        public Criteria andUnlockTitelConfigIsNotNull() {
            addCriterion("UNLOCK_TITEL_CONFIG is not null");
            return (Criteria) this;
        }

        public Criteria andUnlockTitelConfigEqualTo(String value) {
            addCriterion("UNLOCK_TITEL_CONFIG =", value, "unlockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andUnlockTitelConfigNotEqualTo(String value) {
            addCriterion("UNLOCK_TITEL_CONFIG <>", value, "unlockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andUnlockTitelConfigGreaterThan(String value) {
            addCriterion("UNLOCK_TITEL_CONFIG >", value, "unlockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andUnlockTitelConfigGreaterThanOrEqualTo(String value) {
            addCriterion("UNLOCK_TITEL_CONFIG >=", value, "unlockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andUnlockTitelConfigLessThan(String value) {
            addCriterion("UNLOCK_TITEL_CONFIG <", value, "unlockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andUnlockTitelConfigLessThanOrEqualTo(String value) {
            addCriterion("UNLOCK_TITEL_CONFIG <=", value, "unlockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andUnlockTitelConfigLike(String value) {
            addCriterion("UNLOCK_TITEL_CONFIG like", value, "unlockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andUnlockTitelConfigNotLike(String value) {
            addCriterion("UNLOCK_TITEL_CONFIG not like", value, "unlockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andUnlockTitelConfigIn(List<String> values) {
            addCriterion("UNLOCK_TITEL_CONFIG in", values, "unlockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andUnlockTitelConfigNotIn(List<String> values) {
            addCriterion("UNLOCK_TITEL_CONFIG not in", values, "unlockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andUnlockTitelConfigBetween(String value1, String value2) {
            addCriterion("UNLOCK_TITEL_CONFIG between", value1, value2, "unlockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andUnlockTitelConfigNotBetween(String value1, String value2) {
            addCriterion("UNLOCK_TITEL_CONFIG not between", value1, value2, "unlockTitelConfig");
            return (Criteria) this;
        }

        public Criteria andHasTitleConfigIsNull() {
            addCriterion("HAS_TITLE_CONFIG is null");
            return (Criteria) this;
        }

        public Criteria andHasTitleConfigIsNotNull() {
            addCriterion("HAS_TITLE_CONFIG is not null");
            return (Criteria) this;
        }

        public Criteria andHasTitleConfigEqualTo(Integer value) {
            addCriterion("HAS_TITLE_CONFIG =", value, "hasTitleConfig");
            return (Criteria) this;
        }

        public Criteria andHasTitleConfigNotEqualTo(Integer value) {
            addCriterion("HAS_TITLE_CONFIG <>", value, "hasTitleConfig");
            return (Criteria) this;
        }

        public Criteria andHasTitleConfigGreaterThan(Integer value) {
            addCriterion("HAS_TITLE_CONFIG >", value, "hasTitleConfig");
            return (Criteria) this;
        }

        public Criteria andHasTitleConfigGreaterThanOrEqualTo(Integer value) {
            addCriterion("HAS_TITLE_CONFIG >=", value, "hasTitleConfig");
            return (Criteria) this;
        }

        public Criteria andHasTitleConfigLessThan(Integer value) {
            addCriterion("HAS_TITLE_CONFIG <", value, "hasTitleConfig");
            return (Criteria) this;
        }

        public Criteria andHasTitleConfigLessThanOrEqualTo(Integer value) {
            addCriterion("HAS_TITLE_CONFIG <=", value, "hasTitleConfig");
            return (Criteria) this;
        }

        public Criteria andHasTitleConfigIn(List<Integer> values) {
            addCriterion("HAS_TITLE_CONFIG in", values, "hasTitleConfig");
            return (Criteria) this;
        }

        public Criteria andHasTitleConfigNotIn(List<Integer> values) {
            addCriterion("HAS_TITLE_CONFIG not in", values, "hasTitleConfig");
            return (Criteria) this;
        }

        public Criteria andHasTitleConfigBetween(Integer value1, Integer value2) {
            addCriterion("HAS_TITLE_CONFIG between", value1, value2, "hasTitleConfig");
            return (Criteria) this;
        }

        public Criteria andHasTitleConfigNotBetween(Integer value1, Integer value2) {
            addCriterion("HAS_TITLE_CONFIG not between", value1, value2, "hasTitleConfig");
            return (Criteria) this;
        }

        public Criteria andMergecolumnsIsNull() {
            addCriterion("MERGECOLUMNS is null");
            return (Criteria) this;
        }

        public Criteria andMergecolumnsIsNotNull() {
            addCriterion("MERGECOLUMNS is not null");
            return (Criteria) this;
        }

        public Criteria andMergecolumnsEqualTo(String value) {
            addCriterion("MERGECOLUMNS =", value, "mergecolumns");
            return (Criteria) this;
        }

        public Criteria andMergecolumnsNotEqualTo(String value) {
            addCriterion("MERGECOLUMNS <>", value, "mergecolumns");
            return (Criteria) this;
        }

        public Criteria andMergecolumnsGreaterThan(String value) {
            addCriterion("MERGECOLUMNS >", value, "mergecolumns");
            return (Criteria) this;
        }

        public Criteria andMergecolumnsGreaterThanOrEqualTo(String value) {
            addCriterion("MERGECOLUMNS >=", value, "mergecolumns");
            return (Criteria) this;
        }

        public Criteria andMergecolumnsLessThan(String value) {
            addCriterion("MERGECOLUMNS <", value, "mergecolumns");
            return (Criteria) this;
        }

        public Criteria andMergecolumnsLessThanOrEqualTo(String value) {
            addCriterion("MERGECOLUMNS <=", value, "mergecolumns");
            return (Criteria) this;
        }

        public Criteria andMergecolumnsLike(String value) {
            addCriterion("MERGECOLUMNS like", value, "mergecolumns");
            return (Criteria) this;
        }

        public Criteria andMergecolumnsNotLike(String value) {
            addCriterion("MERGECOLUMNS not like", value, "mergecolumns");
            return (Criteria) this;
        }

        public Criteria andMergecolumnsIn(List<String> values) {
            addCriterion("MERGECOLUMNS in", values, "mergecolumns");
            return (Criteria) this;
        }

        public Criteria andMergecolumnsNotIn(List<String> values) {
            addCriterion("MERGECOLUMNS not in", values, "mergecolumns");
            return (Criteria) this;
        }

        public Criteria andMergecolumnsBetween(String value1, String value2) {
            addCriterion("MERGECOLUMNS between", value1, value2, "mergecolumns");
            return (Criteria) this;
        }

        public Criteria andMergecolumnsNotBetween(String value1, String value2) {
            addCriterion("MERGECOLUMNS not between", value1, value2, "mergecolumns");
            return (Criteria) this;
        }

        public Criteria andBusinessDescIsNull() {
            addCriterion("BUSINESS_DESC is null");
            return (Criteria) this;
        }

        public Criteria andBusinessDescIsNotNull() {
            addCriterion("BUSINESS_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessDescEqualTo(String value) {
            addCriterion("BUSINESS_DESC =", value, "businessDesc");
            return (Criteria) this;
        }

        public Criteria andBusinessDescNotEqualTo(String value) {
            addCriterion("BUSINESS_DESC <>", value, "businessDesc");
            return (Criteria) this;
        }

        public Criteria andBusinessDescGreaterThan(String value) {
            addCriterion("BUSINESS_DESC >", value, "businessDesc");
            return (Criteria) this;
        }

        public Criteria andBusinessDescGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_DESC >=", value, "businessDesc");
            return (Criteria) this;
        }

        public Criteria andBusinessDescLessThan(String value) {
            addCriterion("BUSINESS_DESC <", value, "businessDesc");
            return (Criteria) this;
        }

        public Criteria andBusinessDescLessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_DESC <=", value, "businessDesc");
            return (Criteria) this;
        }

        public Criteria andBusinessDescLike(String value) {
            addCriterion("BUSINESS_DESC like", value, "businessDesc");
            return (Criteria) this;
        }

        public Criteria andBusinessDescNotLike(String value) {
            addCriterion("BUSINESS_DESC not like", value, "businessDesc");
            return (Criteria) this;
        }

        public Criteria andBusinessDescIn(List<String> values) {
            addCriterion("BUSINESS_DESC in", values, "businessDesc");
            return (Criteria) this;
        }

        public Criteria andBusinessDescNotIn(List<String> values) {
            addCriterion("BUSINESS_DESC not in", values, "businessDesc");
            return (Criteria) this;
        }

        public Criteria andBusinessDescBetween(String value1, String value2) {
            addCriterion("BUSINESS_DESC between", value1, value2, "businessDesc");
            return (Criteria) this;
        }

        public Criteria andBusinessDescNotBetween(String value1, String value2) {
            addCriterion("BUSINESS_DESC not between", value1, value2, "businessDesc");
            return (Criteria) this;
        }

        public Criteria andCreatorPhoneIsNull() {
            addCriterion("CREATOR_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andCreatorPhoneIsNotNull() {
            addCriterion("CREATOR_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorPhoneEqualTo(String value) {
            addCriterion("CREATOR_PHONE =", value, "creatorPhone");
            return (Criteria) this;
        }

        public Criteria andCreatorPhoneNotEqualTo(String value) {
            addCriterion("CREATOR_PHONE <>", value, "creatorPhone");
            return (Criteria) this;
        }

        public Criteria andCreatorPhoneGreaterThan(String value) {
            addCriterion("CREATOR_PHONE >", value, "creatorPhone");
            return (Criteria) this;
        }

        public Criteria andCreatorPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR_PHONE >=", value, "creatorPhone");
            return (Criteria) this;
        }

        public Criteria andCreatorPhoneLessThan(String value) {
            addCriterion("CREATOR_PHONE <", value, "creatorPhone");
            return (Criteria) this;
        }

        public Criteria andCreatorPhoneLessThanOrEqualTo(String value) {
            addCriterion("CREATOR_PHONE <=", value, "creatorPhone");
            return (Criteria) this;
        }

        public Criteria andCreatorPhoneLike(String value) {
            addCriterion("CREATOR_PHONE like", value, "creatorPhone");
            return (Criteria) this;
        }

        public Criteria andCreatorPhoneNotLike(String value) {
            addCriterion("CREATOR_PHONE not like", value, "creatorPhone");
            return (Criteria) this;
        }

        public Criteria andCreatorPhoneIn(List<String> values) {
            addCriterion("CREATOR_PHONE in", values, "creatorPhone");
            return (Criteria) this;
        }

        public Criteria andCreatorPhoneNotIn(List<String> values) {
            addCriterion("CREATOR_PHONE not in", values, "creatorPhone");
            return (Criteria) this;
        }

        public Criteria andCreatorPhoneBetween(String value1, String value2) {
            addCriterion("CREATOR_PHONE between", value1, value2, "creatorPhone");
            return (Criteria) this;
        }

        public Criteria andCreatorPhoneNotBetween(String value1, String value2) {
            addCriterion("CREATOR_PHONE not between", value1, value2, "creatorPhone");
            return (Criteria) this;
        }

        public Criteria andTipsIsNull() {
            addCriterion("TIPS is null");
            return (Criteria) this;
        }

        public Criteria andTipsIsNotNull() {
            addCriterion("TIPS is not null");
            return (Criteria) this;
        }

        public Criteria andTipsEqualTo(String value) {
            addCriterion("TIPS =", value, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsNotEqualTo(String value) {
            addCriterion("TIPS <>", value, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsGreaterThan(String value) {
            addCriterion("TIPS >", value, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsGreaterThanOrEqualTo(String value) {
            addCriterion("TIPS >=", value, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsLessThan(String value) {
            addCriterion("TIPS <", value, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsLessThanOrEqualTo(String value) {
            addCriterion("TIPS <=", value, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsLike(String value) {
            addCriterion("TIPS like", value, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsNotLike(String value) {
            addCriterion("TIPS not like", value, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsIn(List<String> values) {
            addCriterion("TIPS in", values, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsNotIn(List<String> values) {
            addCriterion("TIPS not in", values, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsBetween(String value1, String value2) {
            addCriterion("TIPS between", value1, value2, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsNotBetween(String value1, String value2) {
            addCriterion("TIPS not between", value1, value2, "tips");
            return (Criteria) this;
        }

        public Criteria andExtButtonsIsNull() {
            addCriterion("EXT_BUTTONS is null");
            return (Criteria) this;
        }

        public Criteria andExtButtonsIsNotNull() {
            addCriterion("EXT_BUTTONS is not null");
            return (Criteria) this;
        }

        public Criteria andExtButtonsEqualTo(String value) {
            addCriterion("EXT_BUTTONS =", value, "extButtons");
            return (Criteria) this;
        }

        public Criteria andExtButtonsNotEqualTo(String value) {
            addCriterion("EXT_BUTTONS <>", value, "extButtons");
            return (Criteria) this;
        }

        public Criteria andExtButtonsGreaterThan(String value) {
            addCriterion("EXT_BUTTONS >", value, "extButtons");
            return (Criteria) this;
        }

        public Criteria andExtButtonsGreaterThanOrEqualTo(String value) {
            addCriterion("EXT_BUTTONS >=", value, "extButtons");
            return (Criteria) this;
        }

        public Criteria andExtButtonsLessThan(String value) {
            addCriterion("EXT_BUTTONS <", value, "extButtons");
            return (Criteria) this;
        }

        public Criteria andExtButtonsLessThanOrEqualTo(String value) {
            addCriterion("EXT_BUTTONS <=", value, "extButtons");
            return (Criteria) this;
        }

        public Criteria andExtButtonsLike(String value) {
            addCriterion("EXT_BUTTONS like", value, "extButtons");
            return (Criteria) this;
        }

        public Criteria andExtButtonsNotLike(String value) {
            addCriterion("EXT_BUTTONS not like", value, "extButtons");
            return (Criteria) this;
        }

        public Criteria andExtButtonsIn(List<String> values) {
            addCriterion("EXT_BUTTONS in", values, "extButtons");
            return (Criteria) this;
        }

        public Criteria andExtButtonsNotIn(List<String> values) {
            addCriterion("EXT_BUTTONS not in", values, "extButtons");
            return (Criteria) this;
        }

        public Criteria andExtButtonsBetween(String value1, String value2) {
            addCriterion("EXT_BUTTONS between", value1, value2, "extButtons");
            return (Criteria) this;
        }

        public Criteria andExtButtonsNotBetween(String value1, String value2) {
            addCriterion("EXT_BUTTONS not between", value1, value2, "extButtons");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bass_query_main
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bass_query_main
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}